---
title: Portmanteau Test
# subtitle:
author: Kenichiro Tamaki
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    number_sections: yes
css: style.css
# csl: apa.csl
# bibliography: references.bib
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```

<p><br></p>

# 関数の作成

## Portmanteau Test

```{r}
port <- function(x, lag, fitdf) { # x = 標本, lag = ラグ, fitdf = 自由度の減数
  res <- Box.test(x, lag = lag, type = "Ljung-Box", fitdf = fitdf) # かばん検定
#  res <- c(lag, res$statistic, res$parameter, res$p.value) # ラグ, 検定統計量, 自由度, p 値
#  names(res) <- c("m", "Q(m)", "df", "p.value") # 名称
  res <- res$statistic # 検定統計量

  return(res)
}
```

出力例

```{r}
T <- 100 # 標本数
p <- 1; ar <- 0.5 # AR 次数; AR 係数
fitdf <- 0 # 自由度の減数
lag <- 1 + fitdf # ラグ
# AR(p) の模擬データ
x <- arima.sim(n = T, # 標本数
               list(order = c(p, 0, 0), ar = ar)) # AR 次数, AR 係数
port(x, lag, fitdf)
```

## シミュレーション

```{r}
port.sim <- function(T, p, ar, mu, # T = 標本数, p = AR 次数, ar = AR 係数, mu = 平均
                     include.mean, fixed, lag, fitdf) { # include.mean = 推定平均, fixed = 推定係数, lag = ラグ, fitdf = 自由度の減数
  # AR(p) の模擬データを作成
  x <- arima.sim(n = T, # 標本数
                 list(order = c(p, 0, 0), ar = ar)) # AR 次数, AR 係数
  x <- mu + x  # 平均を加算

  # AR(p) で模擬データを推定
  est <- arima(x, # 模擬データ
               order = c(p, 0, 0), # AR 次数
               include.mean = include.mean, # 推定平均 
               transform.pars = F, # 変換しない
               fixed = fixed, # 推定係数
               method = "CSS") # 条件付最小 2 乗法 

  res <- sapply(lag, port, x = est$residuals, fitdf = fitdf) # x と fitdf に対して各 lag の port を計算

  return(res)
}
```

出力例

```{r}
mu <- 2 # 平均
include.mean <- TRUE # 推定平均
fixed <- rep(NA, p + 1) # 推定係数
fitdf <- 0 # 自由度の減数
lag <- 1:4 + fitdf # ラグ
port.sim(T, p, ar, mu, include.mean, fixed, lag, fitdf)
```

## QQ plot

```{r}
port.res.qqplot <- function(x, lag, fitdf) { # x = シミュレーション結果, lag = ラグ, fitdf = 自由度の減数
  n.lag <- length(lag) # ラグ数

  for(i in 1:n.lag) {
    # QQ plot
    qqplot(x[i,], # 標本
           qchisq(ppoints(x[i,]), df = lag[i] - fitdf), # 理論値
           xlab = "x", ylab = "chisq") # ラベル

    # 直線を追加
    abline(a = 0, b = 1, # 切片, 傾き
           col = 2, lty = 2) # 赤色, 点線
  }
}
```

## ヒストグラムと密度関数

```{r}
port.res.hist <- function(x, lag, fitdf) { # x = シミュレーション結果, lag = ラグ, fitdf = 自由度の減数
  n.lag <- length(lag) # ラグ数

  for(i in 1:n.lag) {
    # ヒストグラム
    y.max <- max(dchisq(x[i,], df = lag[i] - fitdf)) + 0.1 # y 軸の最大値
    hist(x[i,], # 標本
         freq = FALSE, # 相対度数
         main = "", # 図題
         ylim = c(0, y.max), # y 軸の範囲
         xlab = "x") # x 軸のラベル

    # 密度関数
    curve(dchisq(x, df = lag[i] - fitdf), # 密度関数
          add = TRUE, # プロットを追加
          col = 2, lty = 2, lwd = 2) # 赤色, 点線, 太線
  }
}
```

## 平均と分散

```{r}
port.res.mv <- function(x, lag, fitdf) { # x = シミュレーション結果, lag = ラグ, fitdf = 自由度の減数
  res <- cbind(lag - fitdf, apply(x, 1, mean), apply(x, 1, var)) # 自由度, 行毎の平均, 行毎の分散
  res <- cbind(lag, res) # ラグを追加
  rownames(res) <- NULL
  colnames(res) <- c("m", "df", "mean", "var") # 列名

  return(res)
}
```

<p><br></p>

# シミュレーション

## 回数

```{r}
n.rep <- 10^(4)
```

## 標本数

```{r}
T <- 500
```

## Data: AR$(1)$, Model: AR$(1)$

**パラメータ**

```{r}
p <- 1; ar <- 0.5; mu <- 2 # AR 次数; AR 係数; 平均
include.mean <- TRUE # 推定平均
fixed <- rep(NA, p + 1) # 推定係数
fitdf <- p # 自由度の減数
lag <- 1:9 + fitdf # ラグ
```

**実行**

```{r}
system.time(x <- replicate(n.rep, port.sim(T, p, ar, mu, include.mean, fixed, lag, fitdf))) # 計算時間
```

**結果**

```{r fig.height = 12, fig.width = 12}
par(mfrow = c(3, 3)) # プロット画面を 3 行 3 列に分割
port.res.qqplot(x, lag, fitdf) # QQ plot
port.res.hist(x, lag, fitdf) # ヒストグラムと密度関数
```

```{r}
res <- port.res.mv(x, lag, fitdf) # 自由度, 平均, 分散
digits <- c(0, 0, 3, 3) # 少数点以下の最大表示桁数
col.names <- c("$m$", "自由度", "平均", "分散") # 列名
caption <- "AR$(1)$ の残差に対するかばん検定の平均と分散" # 表題

# 表を作成
knitr::kable(res, # 結果
             digits = digits, # 少数点以下の最大表示桁数
             col.names = col.names, # 列名
             caption = caption) # 表題
```

## Data: AR$(2)$, Model: AR$(2)$

**パラメータ**

```{r}
p <- 2; ar <- c(0.5, 0.2); mu <- 2 # AR 次数; AR 係数; 平均
include.mean <- TRUE # 推定平均
fixed <- rep(NA, p + 1) # 推定係数
fitdf <- p # 自由度の減数
lag <- 1:9 + fitdf # ラグ
```

**実行**

```{r}
system.time(x <- replicate(n.rep, port.sim(T, p, ar, mu, include.mean, fixed, lag, fitdf))) # 計算時間
```

**結果**

```{r fig.height = 12, fig.width = 12}
par(mfrow = c(3, 3)) # プロット画面を 3 行 3 列に分割
port.res.qqplot(x, lag, fitdf) # QQ plot
port.res.hist(x, lag, fitdf) # ヒストグラムと密度関数 
```

```{r}
res <- port.res.mv(x, lag, fitdf) # 自由度, 平均, 分散
caption <- "AR$(2)$ の残差に対するかばん検定の平均と分散" # 表題

# 表を作成
knitr::kable(res, # 結果
             digits = digits, # 少数点以下の最大表示桁数
             col.names = col.names, # 列名
             caption = caption) # 表題
```

## Data: AR$(3)$, Model: AR$(3)$

**パラメータ**

```{r}
p <- 3; ar <- c(0.4, 0.3, 0.2); mu <- 2 # AR 次数; AR 係数; 平均
include.mean <- TRUE # 推定平均
fixed <- rep(NA, p + 1) # 推定係数
fitdf <- p # 自由度の減数
lag <- 1:9 + fitdf # ラグ
```

**実行**

```{r}
system.time(x <- replicate(n.rep, port.sim(T, p, ar, mu, include.mean, fixed, lag, fitdf))) # 計算時間
```

**結果**

```{r fig.height = 12, fig.width = 12}
par(mfrow = c(3, 3)) # プロット画面を 3 行 3 列に分割
port.res.qqplot(x, lag, fitdf) # QQ plot
port.res.hist(x, lag, fitdf) # ヒストグラムと密度関数 
```

```{r}
res <- port.res.mv(x, lag, fitdf) # 自由度, 平均, 分散
caption <- "AR$(3)$ の残差に対するかばん検定の平均と分散" # 表題

# 表を作成
knitr::kable(res, # 結果
             digits = digits, # 少数点以下の最大表示桁数
             col.names = col.names, # 列名
             caption = caption) # 表題
```

## Data: AR$(3)$ with mean $0$, Model: AR$(3)$

**パラメータ**

```{r}
p <- 3; ar <- c(0.6, -0.4, -0.2); mu <- 0 # AR 次数; AR 係数; 平均
include.mean <- TRUE # 推定平均
fixed <- rep(NA, p + 1) # 推定係数
fitdf <- p # 自由度の減数
lag <- 1:9 + fitdf # ラグ
```

**実行**

```{r}
system.time(x <- replicate(n.rep, port.sim(T, p, ar, mu, include.mean, fixed, lag, fitdf))) # 計算時間
```

**結果**

```{r fig.height = 12, fig.width = 12}
par(mfrow = c(3, 3)) # プロット画面を 3 行 3 列に分割
port.res.qqplot(x, lag, fitdf) # QQ plot
port.res.hist(x, lag, fitdf) # ヒストグラムと密度関数 
```

```{r}
res <- port.res.mv(x, lag, fitdf) # 自由度, 平均, 分散
caption <- "AR$(3)'$ の残差に対するかばん検定の平均と分散" # 表題

# 表を作成
knitr::kable(res, # 結果
             digits = digits, # 少数点以下の最大表示桁数
             col.names = col.names, # 列名
             caption = caption) # 表題
```

## Data: AR$(3)$ with mean $0$, Model: AR$(3)$ with mean $0$

**パラメータ**

```{r}
p <- 3; ar <- c(0.6, -0.4, -0.2); mu <- 0 # AR 次数; AR 係数; 平均
include.mean <- FALSE # 推定平均
fixed <- rep(NA, p) # 推定係数
fitdf <- p # 自由度の減数
lag <- 1:9 + fitdf # ラグ
```

**実行**

```{r}
system.time(x <- replicate(n.rep, port.sim(T, p, ar, mu, include.mean, fixed, lag, fitdf))) # 計算時間
```

**結果**

```{r fig.height = 12, fig.width = 12}
par(mfrow = c(3, 3)) # プロット画面を 3 行 3 列に分割
port.res.qqplot(x, lag, fitdf) # QQ plot
port.res.hist(x, lag, fitdf) # ヒストグラムと密度関数 
```

```{r}
res <- port.res.mv(x, lag, fitdf) # 自由度, 平均, 分散
caption <- "AR$(3)'$ の残差に対するかばん検定の平均と分散" # 表題

# 表を作成
knitr::kable(res, # 結果
             digits = digits, # 少数点以下の最大表示桁数
             col.names = col.names, # 列名
             caption = caption) # 表題
```

## Data: AR$(3)$ with coefficient $0$, Model: AR$(3)$

**パラメータ**

```{r}
p <- 3; ar <- c(0.6, 0, -0.3); mu <- 2 # AR 次数; AR 係数; 平均
include.mean <- TRUE # 推定平均
fixed <- rep(NA, p + 1) # 推定係数
fitdf <- p # 自由度の減数
lag <- 1:9 + fitdf # ラグ
```

**実行**

```{r}
system.time(x <- replicate(n.rep, port.sim(T, p, ar, mu, include.mean, fixed, lag, fitdf))) # 計算時間
```

**結果**

```{r fig.height = 12, fig.width = 12}
par(mfrow = c(3, 3)) # プロット画面を 3 行 3 列に分割
port.res.qqplot(x, lag, fitdf) # QQ plot
port.res.hist(x, lag, fitdf) # ヒストグラムと密度関数 
```

```{r}
res <- port.res.mv(x, lag, fitdf) # 自由度, 平均, 分散
caption <- "AR$(3)'$ の残差に対するかばん検定の平均と分散" # 表題

# 表を作成
knitr::kable(res, # 結果
             digits = digits, # 少数点以下の最大表示桁数
             col.names = col.names, # 列名
             caption = caption) # 表題
```

## Data: AR$(3)$ with coefficient $0$, Model: AR$(3)$ with coefficient $0$

**パラメータ**

```{r}
p <- 3; ar <- c(0.6, 0, -0.3); mu <- 2 # AR 次数; AR 係数; 平均
include.mean <- TRUE # 推定平均
fixed <- c(NA, 0, NA, NA) # 推定係数
fitdf <- p - 1 # 自由度の減数
lag <- 1:9 + fitdf # ラグ
```

**実行**

```{r}
system.time(x <- replicate(n.rep, port.sim(T, p, ar, mu, include.mean, fixed, lag, fitdf))) # 計算時間
```

**結果**

```{r fig.height = 12, fig.width = 12}
par(mfrow = c(3, 3)) # プロット画面を 3 行 3 列に分割
port.res.qqplot(x, lag, fitdf) # QQ plot
port.res.hist(x, lag, fitdf) # ヒストグラムと密度関数 
```

```{r}
res <- port.res.mv(x, lag, fitdf) # 自由度, 平均, 分散
caption <- "AR$(3)''$ の残差に対するかばん検定の平均と分散" # 表題

# 表を作成
knitr::kable(res, # 結果
             digits = digits, # 少数点以下の最大表示桁数
             col.names = col.names, # 列名
             caption = caption) # 表題
```
