---
title: 時系列分析 第 13 回
subtitle: 多変量 GARCH モデル
author: Kenichiro Tamaki
date: 2022 年 7 月 4 日
# date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_depth: 3
    number_sections: yes
css: style.css
# csl: apa.csl
# bibliography: references.bib
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
```

<p><br></p>

## 7.4 多変量 GARCH モデル {-}

**$n$ 変量 GARCH モデル**

$$
\boldsymbol{y}_{t} = \boldsymbol{\mu}_{t} + \boldsymbol{u}_{t} = \boldsymbol{\mu}_{t} + H_{t}^{1 / 2} \boldsymbol{v}_{t}, \quad \boldsymbol{v}_{t} \sim \text{iid} (\boldsymbol{0}, I)
$$

- 変数 $\boldsymbol{y}_{t}$ ($n \times 1$ ベクトル)

- 条件付期待値 $\boldsymbol{\mu}_{t} = E[ \boldsymbol{y}_{t} \vert \Omega_{t-1} ]$ ($n \times 1$ ベクトル)

  - 情報集合 $\Omega_{t} = \{ y_{t}, y_{t - 1}, \dots \}$

  - 自己相関がある場合は VAR, ない場合は定数

- 条件付分散共分散行列 $H_{t} = E[ (\boldsymbol{y}_{t} - \boldsymbol{\mu}_{t}) (\boldsymbol{y}_{t} - \boldsymbol{\mu}_{t})^{\prime} \vert \Omega_{t - 1} ] = E[ \boldsymbol{u}_{t} \boldsymbol{u}_{t}^{\prime} \vert \Omega_{t - 1} ]$ ($n \times n$ 行列)

  - $H_{t}^{1 / 2}$ は次を満たす $n \times n$ 行列
  $$
  H_{t}^{1/2} \left( H_{t}^{1/2} \right)^{\prime} = H_{t}
  $$

- 誤差項 $\boldsymbol{v}_{t}$ の分布には, 正規分布や $t$ 分布を用いる

### 7.4.1 VEC (Vectorization) モデル {-}

**Vectorization**

- $A$ を $m \times n$ 行列とする
$$
A =
\begin{pmatrix}
a_{1, 1} & \dots & a_{1, n} \\
\vdots & \ddots & \vdots \\
a_{m, 1} & \dots & a_{m, n}
\end{pmatrix}
$$
列ベクトルを縦に並べることにより得られる $mn \times 1$ ベクトルを $\text{vec} (A)$ と表す
$$
\text{vec} (A) = (a_{1, 1}, \dots, a_{m, 1}, a_{1, 2}, \dots, a_{m, 2}, \dots, a_{1, n}, \dots, a_{m, n})^{\prime}
$$
- 例
$$
A =
\begin{pmatrix}
1 & 3 & 5 \\
2 & 4 & 6
\end{pmatrix}, \quad
\text{vec} (A) = (1, 2, 3, 4, 5, 6)^{\prime}
$$

**Half-vectorization**

- $A$ を $n \times n$ 対称行列とする. 下三角の成分のみの列ベクトルを縦に並べることにより得られる $\dfrac{1}{2} n (n + 1) \times 1$ ベクトルを $\text{vech} (A)$ と表す
$$
\text{vech} (A) = (a_{1, 1}, \dots, a_{n, 1}, a_{2, 2}, \dots, a_{n, 2}, \dots, a_{n - 1, n - 1}, a_{n, n - 1}, a_{n, n})^{\prime}
$$
- 例
$$
A =
\begin{pmatrix}
1 & 2 & 3 \\
2 & 4 & 5 \\
3 & 5 & 6
\end{pmatrix}, \quad
\text{vech} (A) = (1, 2, 3, 4, 5, 6)^{\prime}
$$

#### VEC$(1,1)$ {-}

$1$ 変量 GARCH モデルの自然な一般化は次である.
$$
\text{vech} (H_{t}) = \boldsymbol{c} + B \text{vech} (H_{t - 1}) + A \text{vech} (\boldsymbol{u}_{t - 1} \boldsymbol{u}_{t - 1}^{\prime})
$$
ここで, $\boldsymbol{c}$ は $\dfrac{1}{2} n (n + 1) \times 1$ ベクトル, $A$, $B$ は $\dfrac{1}{2} n (n + 1) \times \dfrac{1}{2} n (n + 1)$ 行列である.

- $n = 2$ のとき, パラメータ数は $21$

- $n = 3$ のとき, パラメータ数は $78$

パラメータ数が多過ぎるので, 実用は困難である.

#### DVEC$(1,1)$ (diagonal VEC) {-}

VEC において, $A$, $B$ を対角行列とする最も単純なモデルを考える.
$$
h_{ij, t} = c_{ij} + b_{ij} h_{ij, t - 1} + a_{ij} u_{i, t - 1} u_{j, t - 1}
$$

行列表現は次である.
$$
H_{t} = C + B \odot H_{t - 1} + A \odot (\boldsymbol{u}_{t - 1} \boldsymbol{u}_{t - 1}^{\prime})
$$
ここで, $A$, $B$, $C$ は $n \times n$ 対称行列, $\odot$ は成分ごとの積を表すアダマール積 (Hadamard product) である. 

- $n = 2$ のとき, パラメータ数は $9$

- $n = 3$ のとき, パラメータ数は $18$

パラメータ数は少ないが, 条件付分散の相互依存関係は存在しない.

### 7.4.2 BEKK モデルと CCC モデル {-}

#### BEKK$(1,1)$ (Baba, Engle, Kraft and Kroner) {-}

$$
H_{t} = C + B H_{t - 1} B^{\prime} + A \boldsymbol{u}_{t - 1} \boldsymbol{u}_{t - 1}^{\prime} A^{\prime}
$$
ここで, $A$, $B$ は $n \times n$ 行列, $C$ は $n \times n$ 対称行列である. 

- $n = 2$ のとき, パラメータ数は $11$

- $n = 3$ のとき, パラメータ数は $24$

パラメータ数は少なく, 条件付分散の相互依存関係を記述できるので, 良く用いられる.

#### $CCC(1,1)$ (constant conditional correlation) {-}

$H_{t}$ の対角成分は $1$ 変量 GARCH モデルとする.
$$
h_{ii, t} = c_{i} + b_{ii} h_{ii, t - 1} + a_{ii} u_{i, t - 1}^{2}
$$

$H_{t}$ の非対角成分は, 相関 $\rho_{ij}$ を用いて次とする.
$$
h_{ij, t} = \rho_{ij} \sqrt{h_{ii, t} h_{jj, t}}
$$

- $n = 2$ のとき, パラメータ数は $7$

- $n = 3$ のとき, パラメータ数は $12$

相関は一定であるので, 一般的に DCC (dynamic conditional correlation) モデルを用いる. 

## 7.5 相関変動モデル {-}

上記の多変量 GARCH モデルは, 条件付分散や共分散のモデル化であり, 相関係数は間接的に変動する. CCC モデルでは相関は一定である. しかし, 変数間の動学的関係の分析においては相関係数が重要であり, 直接的なモデル化が必要となる.

### 7.5.1 DCC モデル {-}

**DCC$(1,1)$**

$$
H_{t} = D_{t} R_{t} D_{t}
$$
ここで, $D_{t} = \text{diag} (H_{t})$, $R_{t}$ は相関行列で
$$
\begin{align}
& R_{t} = \text{diag} (Q_{t})^{-1/2} Q_{t} \text{diag} (Q_{t})^{-1 / 2} \\
& Q_{t} = (1 - a - b) \bar{Q} + b Q_{t - 1} + a \boldsymbol{\varepsilon}_{t - 1} \boldsymbol{\varepsilon}_{t - 1}^{\prime}
\end{align}
$$
また, $\boldsymbol{\varepsilon}_{t} = D_{t}^{-1} \boldsymbol{u}_{t}$, $\bar{Q}$ は $\boldsymbol{\varepsilon}_{t}$ の無条件相関行列である.